import { Component } from '@angular/core';

/**
 * Home component for the app
 */
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: []
})
export class HomeComponent {

  constructor() {
    // Empty constructor generated by default
  }

}
